# Generated by Django 4.2.7 on 2023-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email_Address', models.CharField(max_length=20)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('User_Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('Age', models.CharField(choices=[('under18', 'Under 18'), ('18to30', '18 to 30'), ('31to50', '31 to 50'), ('over50', 'Over 50')], default='under18', max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
