# Generated by Django 4.2.7 on 2023-12-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email_Address', models.CharField(max_length=60)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('User_Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('Age', models.CharField(choices=[('under18', 'Under 18'), ('18to30', '18 to 30'), ('31to50', '31 to 50'), ('over50', 'Over 50')], default='under18', max_length=20)),
                ('Password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('music', 'Music'), ('gaming', 'Gaming'), ('travel', 'Travel')], max_length=100)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=50)),
                ('recording_date', models.DateField()),
                ('license', models.CharField(choices=[('all-rights-reserved', 'All Rights Reserved'), ('cc-by', 'Creative Commons - Attribution'), ('cc-by-sa', 'Creative Commons - Attribution-ShareAlike'), ('public-domain', 'Public Domain'), ('cc-by-nc', 'Creative Commons - Attribution-NonCommercial'), ('cc-by-nc-sa', 'Creative Commons - Attribution-NonCommercial-ShareAlike'), ('cc-by-nd', 'Creative Commons - Attribution-NoDerivs')], max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VideoShare.account')),
            ],
        ),
    ]
