# Generated by Django 4.2.7 on 2023-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('age', models.CharField(choices=[('under18', 'Under 18'), ('18to30', '18 to 30'), ('31to50', '31 to 50'), ('over50', 'Over 50')], max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
